#!/usr/bin/env python3
"""Generate a compact UTF-8/CJK bitmap font header for launcHER.

The generator downloads a pinned GNU Unifont HEX file, extracts only glyphs
that are actually referenced by C/H/CNF/CFG files under the source tree, and
emits a sparse Unicode -> 16x16 monochrome table.

This keeps the ELF small while allowing the launcher source itself to be
written in UTF-8 Chinese. If a Chinese character is added to a launcher error
message, the next CI build automatically includes its glyph.
"""

import argparse
import gzip
import os
import re
import sys
import urllib.request
from pathlib import Path

UNIFONT_VERSION = "18.0.01"
DEFAULT_URL = (
    "https://unifoundry.com/pub/unifont/unifont-18.0.01/"
    "font-builds/unifont-18.0.01.hex.gz"
)

# Common CJK punctuation and forms that may be needed even if a source file
# currently contains no Chinese punctuation literal.
BASE_CODEPOINTS = {
    0x3001, 0x3002, 0x3008, 0x3009, 0x300A, 0x300B, 0x300C, 0x300D,
    0x300E, 0x300F, 0x3010, 0x3011, 0xFF01, 0xFF08, 0xFF09, 0xFF1A,
    0xFF1B, 0xFF1F, 0xFF3B, 0xFF3D, 0xFF5E, 0xFFE5,
}

# Keep scanning focused on CJK so UTF-8 comments/whitespace/European text do
# not accidentally enlarge the generated font.
CJK_RANGES = (
    (0x2000, 0x206F),   # General punctuation
    (0x3000, 0x303F),   # CJK symbols and punctuation
    (0x3400, 0x4DBF),   # CJK Extension A
    (0x4E00, 0x9FFF),   # CJK Unified Ideographs
    (0xF900, 0xFAFF),   # CJK compatibility ideographs
    (0xFF01, 0xFFEF),   # Fullwidth/halfwidth forms
)

VALID_SUFFIXES = {".c", ".h", ".cnf", ".cfg"}


def download(url: str, cache_dir: Path) -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    target = cache_dir / f"unifont-{UNIFONT_VERSION}.hex.gz"
    if target.exists() and target.stat().st_size > 0:
        return target

    print(f"Downloading GNU Unifont {UNIFONT_VERSION}...")
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "launcHER-CJK-font-generator/1.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        target.write_bytes(response.read())
    return target


def iter_source_files(root: Path):
    if root.is_file():
        if root.suffix.lower() in VALID_SUFFIXES:
            yield root
        return

    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in VALID_SUFFIXES:
            continue
        if any(part in {"build", ".git", ".cache"} for part in path.parts):
            continue
        yield path


def scan_codepoints(roots):
    cps = set(BASE_CODEPOINTS)
    files = 0

    for root in roots:
        for path in iter_source_files(root):
            files += 1
            try:
                text = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue

            # Only collect CJK-ish Unicode codepoints. The CJK test string in
            # main.c therefore also becomes part of the generated table.
            for match in re.finditer(r"[^\x00-\x7F]", text):
                cp = ord(match.group(0))
                if any(start <= cp <= end for start, end in CJK_RANGES):
                    cps.add(cp)

    # The renderer is deliberately limited to the BMP for this compact font.
    cps = {cp for cp in cps if 0 <= cp <= 0xFFFF}
    print(f"Scanned {files} source files; selected {len(cps)} BMP codepoints.")
    return cps


def parse_font(path: Path, wanted):
    glyphs = {}
    with gzip.open(path, "rt", encoding="ascii") as stream:
        for line in stream:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_text, hex_text = line.split(":", 1)
            cp = int(cp_text, 16)
            if cp not in wanted:
                continue
            raw = bytes.fromhex(hex_text)
            if len(raw) == 32:
                glyphs[cp] = raw
            elif len(raw) == 16:
                # 8x16 glyph: center in a 16x16 cell.
                out = bytearray(32)
                for row, value in enumerate(raw):
                    out[row * 2 + 1] = value
                glyphs[cp] = bytes(out)
            else:
                raise ValueError(
                    f"unsupported glyph size for U+{cp:04X}: {len(raw)} bytes"
                )
    return dict(sorted(glyphs.items()))


def emit_header(output: Path, glyphs):
    output.parent.mkdir(parents=True, exist_ok=True)

    with output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("/* Auto-generated by tools/gen_cjk_font.py. Do not edit. */\n")
        out.write("#ifndef LAUNCHER_CJK_FONT_H\n")
        out.write("#define LAUNCHER_CJK_FONT_H\n\n")
        out.write("#include <stddef.h>\n")
        out.write("#include <stdint.h>\n\n")
        out.write(f'#define CJK_FONT_VERSION "{UNIFONT_VERSION}"\n')
        out.write(f"#define CJK_FONT_COUNT {len(glyphs)}u\n")
        out.write("#define CJK_GLYPH_BYTES 32u\n\n")

        out.write(
            "static const uint16_t cjk_codepoints[CJK_FONT_COUNT] "
            "__attribute__((aligned(16))) = {\n"
        )
        cps = list(glyphs)
        for offset in range(0, len(cps), 12):
            chunk = cps[offset : offset + 12]
            out.write("    " + ", ".join(f"0x{cp:04X}" for cp in chunk) + ",\n")
        out.write("};\n\n")

        out.write(
            "static const uint8_t cjk_glyphs[CJK_FONT_COUNT][CJK_GLYPH_BYTES] "
            "__attribute__((aligned(16))) = {\n"
        )
        for cp in cps:
            raw = glyphs[cp]
            out.write("    {\n")
            for offset in range(0, 32, 16):
                chunk = raw[offset : offset + 16]
                out.write(
                    "        " + ", ".join(f"0x{value:02X}" for value in chunk) + ",\n"
                )
            out.write(f"    }}, /* U+{cp:04X} */\n")
        out.write("};\n\n")

        out.write(
            "static inline const uint8_t *cjk_font_find(uint32_t codepoint) {\n"
            "    size_t lo = 0;\n"
            "    size_t hi = CJK_FONT_COUNT;\n"
            "    while (lo < hi) {\n"
            "        const size_t mid = lo + ((hi - lo) >> 1);\n"
            "        const uint16_t key = cjk_codepoints[mid];\n"
            "        if (key == codepoint)\n"
            "            return cjk_glyphs[mid];\n"
            "        if (key < codepoint)\n"
            "            lo = mid + 1;\n"
            "        else\n"
            "            hi = mid;\n"
            "    }\n"
            "    return NULL;\n"
            "}\n\n"
            "#endif\n"
        )

    print(f"Generated {len(glyphs)} glyphs -> {output}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--font", type=Path)
    parser.add_argument("--cache-dir", type=Path, default=Path(".cache/unifont"))
    parser.add_argument("--scan-root", action="append", type=Path, default=[])
    parser.add_argument("--url", default=os.environ.get("UNIFONT_URL", DEFAULT_URL))
    args = parser.parse_args()

    try:
        roots = args.scan_root or [Path.cwd()]
        wanted = scan_codepoints(roots)
        font_path = args.font or download(args.url, args.cache_dir)
        glyphs = parse_font(font_path, wanted)
        missing = sorted(wanted - glyphs.keys())
        if missing:
            print(
                "Warning: %d requested codepoints are absent from Unifont and "
                "will render as '?': %s"
                % (len(missing), ", ".join(f"U+{cp:04X}" for cp in missing[:32])),
                file=sys.stderr,
            )
        if not glyphs:
            raise RuntimeError("no usable CJK glyphs found")
        emit_header(args.output, glyphs)
    except Exception as exc:
        print(f"gen_cjk_font.py: error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
